### PR TITLE
Add terratest to repo

### PR DESCRIPTION
**Pull request by chrisgilmerproj**
This adds terratest to the repo and only tests key creation. The key names are random because they stick around up to 7 days.

```sh
make terratest
```

### CODE REVIEW

**Comment by pjdufour-dds** [comment]
Should we be committing this file examples/simple/.terraform.lock.hcl?

**Comment by pjdufour-dds** [comment]
I've added this block to `main.tf` when adding terratest support.

```
 *
 * ## Testing
 *
 * Run all terratest tests using the `terratest` script.  If using `aws-vault`, you could use `aws-vault exec $AWS_PROFILE -- terratest`.  The `AWS_DEFAULT_REGION` environment variable is required by the tests.  Use `TT_SKIP_DESTROY=1` to not destroy the infrastructure created during the tests.  Use `TT_VERBOSE=1` to log all tests as they are run.  The go test command can be executed directly, too.
 *
```

**Comment by pjdufour-dds** [comment]
I'd recommend using the files from this PR before merging.  https://github.com/dod-iac/terraform-module-template/pull/7

**Comment by chrisgilmerproj** [comment]
Alright, I added the bit about testing and updated the script.

**Pull request merged**
